---
# This playbook removes objects that are no longer used. By used, we mean
# objects labelled with a deployment stamp that is no longer active, i.e.
# neither the previous, current or next static-services are pointing to a
# service labelled with this deployment stamp.
#
# Warning: this playbook has only effects on blue-green compatible apps.

- name: Clean the namespace
  hosts: local
  gather_facts: false

  pre_tasks:
    - name: Check configuration
      ansible.builtin.import_tasks: tasks/check_configuration.yml
    - name: Check apps filter
      ansible.builtin.import_tasks: tasks/check_apps_filter.yml

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting clean playbook ===="
      tags: clean

    - name: Set vars
      ansible.builtin.import_tasks: tasks/set_vars.yml
      tags: clean

    - name: Run tasks for apps
      ansible.builtin.include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - get_objects_for_app
          - clean_app_orphans
      tags:
        - static_service
        - clean
