---
# This playbook creates a cert-manager ACME Issuer for a namespace.
#
# It assumes that cert-manager is already installed on the K8S cluster.
# See the official documentation on how to install it :
# https://cert-manager.io/docs/installation/kubernetes/

- name: Create SSL certificates
  hosts: local
  gather_facts: false

  pre_tasks:
    - import_tasks: tasks/check_configuration.yml

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting create_acme playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - name: Lookup available core applications
      ansible.builtin.set_fact:
        core_apps: "{{ lookup('apps', core_apps_paths) }}"

    - name: Print core_apps
      ansible.builtin.debug:
        var: core_apps
        verbosity: 2

    - name: Set acme_templates
      ansible.builtin.set_fact:
        acme_templates: '{{ core_apps | json_query("[?name==`acme`].services[0].templates[]") | list }}' # noqa jinja[invalid]

    - name: Print acme_templates
      ansible.builtin.debug:
        var: acme_templates
        verbosity: 2

    - name: Create K8s entities
      k8s:
        namespace: "{{ namespace_name }}"
        definition: "{{ lookup('template', item) | from_yaml }}"
      with_items:
        - "{{ acme_templates }}"
      when: env_type not in ('development', 'ci')
