---
# This playbook creates an OpenShift project for a particular
# customer/environment

- hosts: local
  gather_facts: False

  pre_tasks:
    - import_tasks: tasks/validate_customer_name.yml

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting create_project playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - name: Make sure the project exists in OpenShift and is up-to-date
      openshift_raw:
        api_version: v1
        kind: Project
        name: "{{ project_name }}"
        description: "{{ project_description|default(project_display_name)|default(project_name) }}"
        display_name: "{{ project_display_name|default(project_name) }}"
        state: present
      register: new_project
      until: new_project.result is defined and new_project.result.status is success
      retries: 30
      delay: 10
