---
# This playbook creates the ACME controler in a project.
# The definition files are lookups targeting openshift-acme GitHub repository.
# https://github.com/tnozicka/openshift-acme

- hosts: local
  gather_facts: False

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting create_acme playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - name: Create all openshift-acme OpenShift objects
      openshift_raw:
        force: true
        namespace: "{{ project_name }}"
        definition: "{{ lookup('url', acme_git + item + '.yaml', split_lines=False) | from_yaml }}"
      with_items:
        - "{{ acme_openshift_objects }}"
      when: env_type not in ('development', 'ci')

    - name: Add role to serviceaccount
      openshift_raw:
        force: true
        state: present
        definition: "{{ lookup('template', 'apps/_common/templates/rolebinding/add-role-to-sa.yml.j2') | from_yaml }}"
      with_items:
        - "{{ openshift_rolesbinding }}"
      ignore_errors: true
      when: env_type not in ('development', 'ci')
      # The rolebinding is created but openshift_raw fail
      # see this issue
      # https://github.com/ansible/ansible/issues/36845
