---
- name: Create secrets
  hosts: local
  gather_facts: false

  pre_tasks:
    - name: Check configuration
      ansible.builtin.import_tasks: tasks/check_configuration.yml

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting create_secrets playbook ===="
      tags: secret

    - name: Set vars
      ansible.builtin.import_tasks: tasks/set_vars.yml

    - name: Run tasks for apps
      ansible.builtin.include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - tasks/get_vault_for_app
          - tasks/create_app_secrets
      tags: secret

    - name: Create secret for Docker registry
      ansible.builtin.import_tasks: tasks/create_docker_registry_secrets.yml
