---
# This playbook pushes an OpenShift definition file for a project.
#
# A definition file is generated and pushed for a template given the
# `object_template` path.
#
# Usage:
#
#   $ bin/ansible-playbook create_object.yml \
#       -e "object_template=apps/edxapp/job/import_demo_course.yml.j2"
#       -e "deployment_stamp=d-180611-08h46m30s"
#

- hosts: local
  gather_facts: False
  vars:
    object_template: ""

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting create_object playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - name: Print OpenShift object template path
      debug: msg="Object template {{ object_template }}"

    - name: Print deployment stamp
      debug: msg="Deployment stamp {{ deployment_stamp }}"

    # Set the job stamp for this object (only used for jobs)
    - name: Set job stamp
      set_fact: job_stamp="j-{{ lookup('pipe', 'date +%y%m%d-%Hh%Mm%Ss') }}"

    - name: Print job stamp
      debug: msg="Job stamp {{ job_stamp }}"

    - name: Create object
      openshift_raw:
        definition: "{{ lookup('template', object_template) | from_yaml }}"
        state: present
        force: true
