---

- hosts: local
  gather_facts: False
  vars_files:
    - "group_vars/customer/{{ customer }}.yml"
    - "group_vars/env_type/{{ env_type }}.yml"

  tasks:

    # Find all files named "credentials.vault.yml" for a customer in an
    # environment. This file should be yaml formatted and it must define all
    # environment variables required to run an application, _e.g._:
    #
    # # group_vars/secret/credentials.dist.yml
    # DJANGO_SECRET_KEY: this is my key
    # POSTGRESQL_USER: foo
    - name: Find all project specific files related to credentials
      find:
        paths: "group_vars/secret/{{ customer }}/{{ env_type }}"
        pattern: "credentials.vault.yml"
        recurse: yes
      register: vaulted_credentials  # Record the list of files in a variable used below

    # Decrypt vaulted credentials and register them in a credentials new
    # variable
    #
    # Nota bene: you will need to set the vaut password while using this
    # playbook to ensure we can decrypt vaulted credentials
    - name: Decrypt vaulted credentials
      include_vars:
        name: "{{ item.path | relpath('group_vars/secret/' + customer + '/' + env_type) | dirname }}"
        file: "{{ item.path }}"
      with_items: "{{ vaulted_credentials.files }}"
      register: credentials
      when: vaulted_credentials.matched != 0

    # For every credentials file, compile the OpenShift secret object template
    # (see templates/openshift/common/secret/env_vars.yml.j2) given a group (the
    # application, _e.g._ richie or edxapp) and the set of environment variables
    # defined in the above mentionned credentials file.
    #
    # Nota bene: we store all secrets separated by a '||' in the project_secrets
    # variable, to iterate over secrets, you will need to split('||') that
    # variable first.
    - name: set_fact project_secrets
      set_fact:
        project_secrets: |
          {% for item in credentials.results -%}
            {% for group, env_vars in item.ansible_facts.iteritems() -%}
              {% include "templates/openshift/common/secret/env_vars.yml.j2" -%}
            {%- endfor %}
            {% if not loop.last -%}||{% endif -%}
          {%- endfor %}
      when: vaulted_credentials.matched != 0

    # Create all project secrets (for every group)
    - name: Actually create the secrets in OpenShift
      openshift_raw:
        state: present
        force: true
        definition: "{{ item | from_yaml }}"
      with_items: "{{ project_secrets.split('||') }}"
      when: vaulted_credentials.matched != 0
