---
- name: Create volumes
  hosts: local
  gather_facts: false

  pre_tasks:
    - name: Check configuration
      ansible.builtin.import_tasks: tasks/check_configuration.yml

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting create_volumes playbook ===="
      tags: volume

    - name: Set vars
      ansible.builtin.import_tasks: tasks/set_vars.yml

    - name: Run tasks for apps
      ansible.builtin.include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - tasks/create_app_volumes
      tags:
        - volume
