---

- hosts: local
  gather_facts: False

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting create_secrets playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - include_tasks: tasks/create_app_secrets.yml
      loop: "{{ apps }}"
      loop_control:
        loop_var: app
      when: apps is defined
