---

- hosts: local
  gather_facts: False

  pre_tasks:
    - import_tasks: tasks/validate_customer_name.yml

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting create_secrets playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - tasks/get_objects_for_app
          - tasks/create_app_secrets
      tags:
        - secret
