---
# This playbook creates the ACME controler in a project.
# The definition files are lookups targeting openshift-acme GitHub repository.
# https://github.com/tnozicka/openshift-acme

- hosts: local
  gather_facts: False

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting create_acme playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - name: Lookup available core applications
      set_fact: core_apps="{{ [ lookup('apps', 'core_apps/') ] | flatten }}"

    - name: Print core_apps
      debug:
        msg: "{{ core_apps }}"
        verbosity: 2

    - name: Set acme_templates
      set_fact:
        acme_templates: "{{ core_apps | json_query(\"[?name=='acme'].services[0].templates[]\") | list }}"

    - name: Print acme_templates
      debug:
        msg: "{{ acme_templates | to_nice_yaml  }}"
        verbosity: 2

    - name: Set rolebinding template
      set_fact:
        rb_template: "{{ acme_templates | map('regex_search', '.*/rb\\.yml\\.j2$') | select('string') | first }}"

    - name: Print rb_template
      debug:
        msg: "{{ rb_template | to_nice_yaml }}"
        verbosity: 2

    - name: Set role template
      set_fact:
        role_template: "{{ acme_templates | map('regex_search', '.*/role\\.yml\\.j2$') | select('string') | first }}"
      when: has_acme_cluster_role

    - name: Print role_template
      debug:
        msg: "{{ role_template | to_nice_yaml }}"
        verbosity: 2
      when: has_acme_cluster_role

    - name: Set base_acme_templates
      set_fact:
        base_acme_templates: "{{ acme_templates | reject('eq', rb_template) | select('string') | list }}"

    - name: Remove role from base_acme_templates
      set_fact:
        base_acme_templates: "{{ base_acme_templates | reject('eq', role_template) | select('string') | list }}"
      when: has_acme_cluster_role

    - name: Print base_acme_templates
      debug:
        msg: "{{ base_acme_templates | to_nice_yaml }}"
        verbosity: 2

    - name: Create all openshift-acme OpenShift objects
      openshift_raw:
        force: true
        namespace: "{{ project_name }}"
        definition: "{{ lookup('template', item) | from_yaml }}"
      with_items:
        - "{{ base_acme_templates }}"
      when: env_type not in ('development', 'ci')

    - name: Add role to serviceaccount
      openshift_raw:
        force: true
        state: present
        definition: "{{ lookup('template', rb_template) | from_yaml }}"
      ignore_errors: true
      when: env_type not in ('development', 'ci')
      # The rolebinding is created but openshift_raw fail see this issue
      # https://github.com/ansible/ansible/issues/36845
