---
# This playbook pushes a k8s definition file for a project.
#
# A definition file is generated and pushed for a template given the
# `object_template` path.
#
# Usage:
#
#   $ bin/ansible-playbook create_object.yml \
#       -e "object_template=apps/edxapp/job/import_demo_course.yml.j2"
#       -e "deployment_stamp=d-180611-08h46m30s"
#

- name: Create object
  hosts: local
  gather_facts: false
  vars:
    object_template: ""

  pre_tasks:
    - name: Check configuration
      ansible.builtin.import_tasks: tasks/check_configuration.yml

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting create_object playbook ===="
      tags: deploy

    - name: Set vars
      ansible.builtin.import_tasks: tasks/set_vars.yml

    - name: Print OpenShift object template path
      ansible.builtin.debug: msg="Object template {{ object_template }}"

    - name: Print deployment stamp
      ansible.builtin.debug: msg="Deployment stamp {{ deployment_stamp }}"

    # Set the job stamp for this object (only used for jobs)
    - name: Set job stamp
      ansible.builtin.set_fact: job_stamp="j-{{ lookup('pipe', 'date +%y%m%d-%Hh%Mm%Ss') }}"

    - name: Print job stamp
      ansible.builtin.debug: msg="Job stamp {{ job_stamp }}"

    - name: Print compiled template
      ansible.builtin.debug:
        msg: "{{ lookup('template', object_template) }}"
        verbosity: 2

    - name: Create object
      kubernetes.core.k8s:
        definition: "{{ lookup('template', object_template) | from_yaml_all }}"
        state: present
        force: true
