- name: Create ingresses
  hosts: local
  gather_facts: false

  pre_tasks:
    - import_tasks: tasks/check_configuration.yml

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting create_ingresses playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - get_objects_for_app
          - create_app_ingresses
      tags:
        - ingress
