---
# This playbook creates the redirection core app objects.

- hosts: local
  gather_facts: false

  pre_tasks:
    - import_tasks: tasks/check_configuration.yml

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting create_redirect playbook ===="
      tags: deploy

    # Set the deployment stamp value that will be used to make created objects
    # unique.
    - name: Set deployment stamp
      ansible.builtin.set_fact: deployment_stamp="d-{{ lookup('pipe', 'date +%y%m%d-%Hh%Mm%Ss') }}"

    - import_tasks: tasks/set_vars.yml

    - name: Lookup available core applications
      ansible.builtin.set_fact:
        core_apps: "{{ lookup('apps', core_apps_paths) }}"

    - name: Set app to point to the redirect app
      ansible.builtin.set_fact:
        app: '{{ core_apps | json_query("[?name==`redirect`] | [0]") }}'

    - name: Include "all" type vars for redirect app
      include_tasks: tasks/load_app_defaults.yml
      vars:
        file: "{{ item.path }}"
      with_items: '{{ app | json_query("vars[?type==`all`]") }}'

    - import_tasks: tasks/get_objects_for_app.yml

    - import_tasks: tasks/create_app_config.yml

    - name: Create redirect deployments
      k8s:
        force: true
        namespace: "{{ namespace_name }}"
        definition: "{{ lookup('template', deployment) | from_yaml }}"
        state: present
      loop: "{{ deployments }}"
      loop_control:
        loop_var: deployment

    # Check if the nginx service already exists and recreate it only if not
    # (parts of an k8s Service definition are immutable).
    - name: Check if the redirect nginx service already exists
      k8s_info:
        api_version: "v1"
        namespace: "{{ namespace_name }}"
        kind: "Service"
        name: "redirect-nginx"
      register: redirect_nginx_service

    - name: Create redirect services
      k8s:
        namespace: "{{ namespace_name }}"
        definition: "{{ lookup('template', service) | from_yaml }}"
        state: present
      loop: "{{ services }}"
      loop_control:
        loop_var: service
      when: redirect_nginx_service.resources | length == 0

    - import_tasks: tasks/create_redirection_ingresses.yml
