---
# This playbook creates a K8S namespace for a particular
# customer/environment

- hosts: local
  gather_facts: False

  pre_tasks:
    - import_tasks: tasks/check_configuration.yml

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting create_namespace playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - name: Make sure the namespace exists in K8S and is up-to-date
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace_name }}"
            labels: "{{ k8s_namespace_labels | default({}) | combine({ 'name': namespace_name }) }}"
      register: new_namespace
      until: new_namespace.result is defined and new_namespace.result.status is success
      retries: 30
      delay: 10
