---

- name: Create vaults
  hosts: local
  gather_facts: false

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting create_vaults playbook ===="
      tags: deploy

    - name: Set vars
      ansible.builtin.import_tasks: tasks/set_vars.yml

    - name: Run tasks for apps
      ansible.builtin.include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - tasks/create_app_vault
      tags:
        - vault
