---
# This playbook deletes an OpenShift project for a particular
# customer/environment

- hosts: local
  gather_facts: False

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting delete_project playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - name: Delete the project
      openshift_raw:
        api_version: v1
        kind: Project
        name: "{{ project_name }}"
        state: absent
