---
# Delete the previous stack
#
# This playbook may be useful to lower server load with old stack that will
# never be switched back.
- hosts: local
  gather_facts: False

  pre_tasks:
    - import_tasks: tasks/check_configuration.yml
    - import_tasks: tasks/check_apps_filter.yml

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting delete_previous playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - get_objects_for_app
          - deploy_get_stamp_from_static_service
          - delete_app
        prefix: previous
      tags:
        - static_service
        - switch
