---
# Delete the previous stack
#
# This playbook may be useful to lower server load with old stack that will
# never be switched back.
- name: Delete previous stack
  hosts: local
  gather_facts: false

  pre_tasks:
    - name: Check configuration
      ansible.builtin.import_tasks: tasks/check_configuration.yml
    - name: Check apps filter
      ansible.builtin.import_tasks: tasks/check_apps_filter.yml

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting delete_previous playbook ===="
      tags: deploy

    - name: Set vars
      ansible.builtin.import_tasks: tasks/set_vars.yml

    - name: Run tasks for apps
      ansible.builtin.include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - get_objects_for_app
          - deploy_get_stamp_from_static_service
          - delete_app
        prefix: previous
      tags:
        - static_service
        - switch
