---
# This playbook deploys a whole new stack with the current `deployment_stamp`
# (see main.yml)

- hosts: local
  gather_facts: False

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting deploy playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    # Set the deployment stamp value for this deployment
    - name: Set deployment stamp
      set_fact: deployment_stamp="d-{{ lookup('pipe', 'date +%y%m%d-%Hh%Mm%Ss') }}"
      tags: deploy

    # Set the job stamp for this deployment
    - name: Set job stamp
      set_fact: job_stamp="j-{{ lookup('pipe', 'date +%y%m%d-%Hh%Mm%Ss') }}"
      tags: deploy

    - name: Display deployment details
      debug: msg="Deploying {{ project_name }}-{{ domain_name }} (deployment stamp '{{ deployment_stamp }}' job stamp '{{ job_stamp }}')"
      tags: deploy

    - name: Display apps to deploy
      debug: msg="{{ apps | to_nice_yaml }}"
      tags: deploy

    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - tasks/create_app_config
          - tasks/manage_app
      tags:
        - config
        - deploy

    # Patch all next routes of all apps after deploy
    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        prefix: "next"
        tasks:
          - deploy_get_stamp_from_route
          - deploy_patch_route
          - delete_app
      tags:
        - route
        - deploy

    - import_tasks: tasks/create_route_aliases.yml
      tags:
        - route
        - deploy
