---
# This playbook deploys a whole new stack with the current `deployment_stamp`
# (see main.yml)

- hosts: local
  gather_facts: False
  vars_files:
    - "group_vars/customer/{{ customer }}.yml"
    - "group_vars/env_type/{{ env_type }}.yml"

  tasks:

    # Set the deployment stamp value for this deployment
    - name: Set deployment stamp
      set_fact: deployment_stamp="d-{{ lookup('pipe', 'date +%y%m%d-%Hh%Mm%Ss') }}"

    # Set the job stamp for this deployment
    - name: Set job stamp
      set_fact: job_stamp="j-{{ lookup('pipe', 'date +%y%m%d-%Hh%Mm%Ss') }}"

    - name: Print deployment details
      debug: msg="Deploying {{ project_name }} - {{ domain_name }} (deployment stamp '{{ deployment_stamp }}' job stamp '{{ job_stamp }}')"

    - import_tasks: tasks/create_config.yml

    - name: Deploy new stack to OpenShift
      openshift_raw:
        definition: "{{ lookup('template', 'templates/' + item + '.j2') | from_yaml }}"
        state: present
      with_items:
        - "{{ openshift_deployments }}"
        - "{{ openshift_services }}"
        - "{{ openshift_jobs }}"
        - "{{ openshift_routes }}"

    - import_tasks: tasks/create_route_aliases.yml
