---
# This playbook deploys a whole new stack with the current `deployment_stamp`
# (see main.yml)

- hosts: local
  gather_facts: False

  pre_tasks:
    - import_tasks: tasks/check_configuration.yml
    - import_tasks: tasks/check_apps_filter.yml

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting deploy playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    # Set the deployment stamp value for this deployment
    - name: Set deployment stamp
      set_fact: deployment_stamp="d-{{ lookup('pipe', 'date +%y%m%d-%Hh%Mm%Ss') }}"
      tags: deploy

    # Set the job stamp for this deployment
    - name: Set job stamp
      set_fact: job_stamp="j-{{ lookup('pipe', 'date +%y%m%d-%Hh%Mm%Ss') }}"
      tags: deploy

    - name: Display deployment details
      debug: msg="Deploying {{ project_name }}-{{ domain_name }} (deployment stamp '{{ deployment_stamp }}' job stamp '{{ job_stamp }}')"
      tags: deploy

    - name: Display apps to deploy
      debug:
        var: apps
      tags: deploy

    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        suspend_cronjob: True
        tasks:
          - tasks/get_objects_for_app
          - tasks/check_app_secrets
          - tasks/create_app_config
          - tasks/manage_app
      tags:
        - config
        - deploy

    # Patch all next static services of all apps after deploy
    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        prefix: "next"
        tasks:
          - get_objects_for_app
          - deploy_get_stamp_from_static_service
          - deploy_patch_static_service
          - delete_app
      tags:
        - static_service
        - deploy
