---
# This playbook deploys a whole new stack with the current `deployment_stamp`
# (see main.yml)

- hosts: local
  gather_facts: False

  tasks:

    - import_tasks: tasks/set_vars.yml

    # Set the deployment stamp value for this deployment
    - name: Set deployment stamp
      set_fact: deployment_stamp="d-{{ lookup('pipe', 'date +%y%m%d-%Hh%Mm%Ss') }}"

    # Set the job stamp for this deployment
    - name: Set job stamp
      set_fact: job_stamp="j-{{ lookup('pipe', 'date +%y%m%d-%Hh%Mm%Ss') }}"

    - name: Print deployment details
      debug: msg="Deploying {{ project_name }} - {{ domain_name }} (deployment stamp '{{ deployment_stamp }}' job stamp '{{ job_stamp }}')"

    - include_tasks: tasks/create_config.yml
      loop: "{{ apps }}"
      loop_control:
        loop_var: app
      when: apps is defined

    - name: Deploy new stack to OpenShift
      openshift_raw:
        definition: "{{ lookup('template', 'apps/' + item + '.j2') | from_yaml }}"
        state: present
      with_items:
        - "{{ openshift_deployments }}"
        - "{{ openshift_services }}"
        - "{{ openshift_jobs }}"
        - "{{ openshift_routes }}"

    - import_tasks: tasks/create_route_aliases.yml
