---
- name: Fetch project dependencies
  hosts: local
  gather_facts: false

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting fetch_dependencies playbook ===="

    - name: Check application registry
      ansible.builtin.stat:
        path: "{{ apps_registry_file_name }}"
      register: registry_file

    - name: Loading default registry (if missing)
      ansible.builtin.get_url:
        url: "{{ default_apps_registry_url }}"
        dest: "{{ apps_registry_file_name }}"
        mode: "u=rw"
      when: not registry_file.stat.exists

    - name: Re-check application registry
      ansible.builtin.stat:
        path: "{{ apps_registry_file_name }}"
      register: registry_file

    - name: Application registry checkpoint
      block:
        - name: Abort if registry file does not exist
          ansible.builtin.debug:
            msg: "No registry file found"
        - name: Exit playbook
          ansible.builtin.meta: end_play
      when: not registry_file.stat.exists

    - name: Load registry
      ansible.builtin.include_vars:
        file: "{{ apps_registry_file_name }}"
        name: registry
      when: registry_file.stat.exists

    - name: Display registry
      ansible.builtin.debug:
        var: registry
        verbosity: 1

    - name: Check dependencies files
      ansible.builtin.stat:
        path: "{{ dependencies_file_name }}"
      register: dependencies_file

    - name: Dependencies checkpoint
      block:
        - name: Abort if dependencies file does not exist
          ansible.builtin.debug:
            msg: "No dependencies file found"
        - name: Exit playbook
          ansible.builtin.meta: end_play
      when: not dependencies_file.stat.exists

    - name: Load dependencies
      ansible.builtin.include_vars:
        file: "{{ dependencies_file_name }}"
      when: dependencies_file.stat.exists

    - name: Display dependencies
      ansible.builtin.debug:
        var: dependencies
        verbosity: 1

    - name: Fetch dependencies locally
      ansible.builtin.include_tasks: tasks/fetch_app.yml
      loop: "{{ dependencies }}"
      loop_control:
        loop_var: dependency
