---

- import_playbook: create_project.yml
- import_playbook: create_secrets.yml
- import_playbook: create_acme.yml

- hosts: local
  gather_facts: False

  tasks:

    - import_tasks: tasks/set_vars.yml

    - name: Print project details
      debug: msg="Project name {{ project_name }} - domain {{ domain_name }}"

    - name: Make sure base objects exist in OpenShift and are up-to-date
      openshift_raw:
        definition: "{{ lookup('template', 'templates/' + item + '.j2') | from_yaml }}"
        state: present
      with_items:
        - "{{ openshift_volumes }}"
        - "{{ openshift_endpoints }}"
      when: item is not none

    - import_tasks: tasks/create_route_aliases.yml
