- import_playbook: create_project.yml
- import_playbook: create_volumes.yml
- import_playbook: create_htpasswds.yml
  when: activate_http_basic_auth
- import_playbook: create_secrets.yml
- import_playbook: create_acme.yml

- hosts: local
  gather_facts: False

  pre_tasks:
    - import_tasks: tasks/validate_configuration.yml

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting init_project playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - import_tasks: tasks/create_route_aliases.yml

    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - get_objects_for_app
          - create_static_services_routes
          - create_app_image_streams
      tags:
        - volume
        - route
        - stream
