---

- import_playbook: create_project.yml
- import_playbook: create_secrets.yml
- import_playbook: create_acme.yml

- hosts: local
  gather_facts: False

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting init_project playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml


    - import_tasks: tasks/create_route_aliases.yml

    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - get_objects_for_app
          - create_app_volumes
          - create_app_endpoints
          - create_static_services_routes
      tags:
        - volume
        - endpoint
        - route
