---
# This playbook runs the load_fixtures job to import a demo course
# and create demo users
#

- hosts: local
  gather_facts: false
  vars:
    load_fixtures_template: "apps/edxapp/job/load_fixtures.yml.j2"

  pre_tasks:
    - import_tasks: tasks/check_configuration.yml

  tasks:
    - import_tasks: tasks/set_vars.yml

    - name: Print Object template
      ansible.builtin.debug: msg="Object template {{ load_fixtures_template }}"

    - name: Import demo course and create demo users
      k8s:
        definition: "{{ lookup('template', load_fixtures_template) | from_yaml }}"
        state: present
        force: true
