---
# This playbook rolls back all static services:
# 1. point the "current" static service to the stack that was pointed by the "previous" static service,
# 2. point the "next" static service to the stack that was pointed by the "current" static service,

- name: Rollback the previous stack
  hosts: local
  gather_facts: false

  pre_tasks:
    - import_tasks: tasks/check_configuration.yml
    - import_tasks: tasks/check_apps_filter.yml

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting rollback playbook ===="
      tags: rollback

    - import_tasks: tasks/set_vars.yml
      tags: rollback

    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - get_objects_for_app
          - rollback_static_services
      tags:
        - static_service
        - rollback
