---
# This playbook switches all static services:
# 1. point the "previous" static service to the stack that was pointed by the "current" static service,
# 2. point the "current" static service to the stack that was pointed by the "next" static service,
# 3. delete the stack that was pointed by the "previous" static service,
# 4. patch the next static service to the init stamp

- name: Switch stacks
  hosts: local
  gather_facts: false

  pre_tasks:
    - import_tasks: tasks/check_configuration.yml
    - import_tasks: tasks/check_apps_filter.yml

  tasks:
    - name: Display playbook name
      ansible.builtin.debug: msg="==== Starting switch playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - get_objects_for_app
          - switch_static_services
          - switch_cronjobs
      tags:
        - static_service
        - switch
