---
# This playbook switch all routes:
# 1. point the "current" route to the stack that was pointed by the "next" route,
# 2. point the "previous" route to the stack that was pointed by the "current" route just before we changed it in 1)
# 3. delete the stack that was pointed by the "previous" route just before we changed it in 2)
# 4. patch the next route to the init stamp

- hosts: local
  gather_facts: False

  tasks:

    - import_tasks: tasks/set_vars.yml

    # Patch all apps dest routes with src stack
    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - switch_routes
      tags:
        - route
        - switch
