---
# This playbook switch all routes:
# 1. point the "previous" route to the stack that was pointed by the "current" route,
# 2. point the "current" route to the stack that was pointed by the "next" route,
# 3. delete the stack that was pointed by the "previous" route,
# 4. patch the next route to the init stamp

- hosts: local
  gather_facts: False

  pre_tasks:
    - import_tasks: tasks/validate_configuration.yml

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting switch playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - include_tasks: tasks/run_tasks_for_apps.yml
      vars:
        tasks:
          - get_objects_for_app
          - switch_routes
      tags:
        - route
        - switch
