# ---- DockerHub publication job ----
hub:
  # We use the machine executor, i.e. a VM, not a container
  machine:
    # Prevent cache-related issues
    docker_layer_caching: false

  working_directory: ~/fun

  steps:
    - checkout
    - *attach_workspace
    - *docker_load
    - *ci_env
    # Login to DockerHub to Publish new images
    #
    # Nota bene: you'll need to define the following secrets environment vars
    # in CircleCI interface:
    #
    #   - DOCKER_USER
    #   - DOCKER_PASS
    - run:
        name: Login to DockerHub
        command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

    # Tag docker images with the same pattern used in Git (Semantic Versioning)
    #
    # Git tag: v1.0.1
    # Docker tag: 1.0.1
    - run:
        name: Tag images
        command: |
          docker images fundocker/arnold
          DOCKER_TAG=$([[ -z "$CIRCLE_TAG" ]] && echo $CIRCLE_BRANCH || echo ${CIRCLE_TAG} | sed 's/^v//')
          RELEASE_TYPE=$([[ -z "$CIRCLE_TAG" ]] && echo "branch" || echo "tag ")
          # Display either:
          # - DOCKER_TAG: master (Git branch)
          # or
          # - DOCKER_TAG: 1.1.2 (Git tag v1.1.2)
          echo "DOCKER_TAG: ${DOCKER_TAG} (Git ${RELEASE_TYPE}${CIRCLE_TAG})"
          docker tag ${ARNOLD_IMAGE} fundocker/arnold:${DOCKER_TAG}
          if [[ -n "$CIRCLE_TAG" ]]; then
            docker tag ${ARNOLD_IMAGE} fundocker/arnold:latest
          fi
          docker images | grep -E "^fundocker/arnold\s*(${DOCKER_TAG}.*|latest|master)"
    - run:
        name: Publish images
        command: |
          DOCKER_TAG=$([[ -z "$CIRCLE_TAG" ]] && echo $CIRCLE_BRANCH || echo ${CIRCLE_TAG} | sed 's/^v//')
          RELEASE_TYPE=$([[ -z "$CIRCLE_TAG" ]] && echo "branch" || echo "tag ")
          # Display either:
          # - DOCKER_TAG: master (Git branch)
          # or
          # - DOCKER_TAG: 1.1.2 (Git tag v1.1.2)
          echo "DOCKER_TAG: ${DOCKER_TAG} (Git ${RELEASE_TYPE}${CIRCLE_TAG})"
          docker push fundocker/arnold:${DOCKER_TAG}
          if [[ -n "$CIRCLE_TAG" ]]; then
            docker push fundocker/arnold:latest
          fi
