# Check expected app secrets exists. This is useful to avoid deploying an
# application for which secrets have not been created first.

- name: Does current app has secrets?
  set_fact:
    app_has_secrets: "{{
      app |
      json_query('services[*].templates[]') |
      map('regex_search', '.*/secret.*\\.yml\\.j2$') |
      select('string') | list | length > 0
    }}"
  tags: secret

- name: "Get created application secrets for {{ app.name }}"
  k8s_facts:
    api_version: "v1"
    namespace: "{{ project_name }}"
    kind: Secret
    label_selectors:
      - app={{ app.name }}
  register: existing_secrets
  when: app_has_secrets
  tags: secret

- name: "Filter secrets matching expected checksum {{ lookup('vars', app.name + '_vault_checksum') }}"
  set_fact:
    selected_secret_names: "{{
      existing_secrets |
      json_query('resources[].metadata.name') |
      select('match', '.*-' + lookup('vars', app.name + '_vault_checksum')) | list
    }}"
  when: app_has_secrets
  tags: secret

- name: Check if secrets matching the current application vault checksum exists
  fail:
    msg: "Application secrets should be created first"
  when: app_has_secrets and selected_secret_names | length < 1
  tags: secret
