# Check expected app secrets exists. This is useful to avoid deploying an
# application for which secrets have not been created first.

- name: Does current app has secrets?
  set_fact:
    app_has_secrets: "{{
      app |
      json_query('services[*].templates[]') |
      map('regex_search', '.*/secret.*\\.yml\\.j2$') |
      select('string') | list | length > 0
    }}"
    app_should_check_secrets: true
  tags: secret

- name: Handle permission on Secret objects
  block:
    - name: "Get created application secrets for {{ app.name }}"
      k8s_info:
        api_version: "v1"
        namespace: "{{ namespace_name }}"
        kind: Secret
        label_selectors:
          - app={{ app.name }}
      register: existing_secrets
  rescue:
    - name: Debug k8s query failure
      debug:
        msg: >
          Cannot get created secrets for application "{{ app.name }}". Logged user probably
          does not have permissions for this kind of object!
    - name: Ignore app secrets checking
      set_fact:
        app_should_check_secrets: false
  when: app_has_secrets
  tags: secret

- name: "Filter secrets matching expected checksum {{ lookup('vars', app.name + '_vault_checksum') }}"
  set_fact:
    selected_secret_names: "{{
      existing_secrets |
      json_query('resources[].metadata.name') |
      select('match', '.*-' + lookup('vars', app.name + '_vault_checksum')) | list
    }}"
  when: app_has_secrets and app_should_check_secrets
  tags: secret

- name: Check if secrets matching the current application vault checksum exists
  fail:
    msg: "Application secrets should be created first"
  when: app_has_secrets and app_should_check_secrets and selected_secret_names | length < 1
  tags: secret
