---
# Create static routes for services of an app

- name: "Make sure static route exists for the '{{ app.name }}' app"
  include_tasks: tasks/deploy_patch_route.yml
  loop: "{{ blue_green_route_prefixes }}"
  loop_control:
    loop_var: prefix
  when: routes | length > 0
  tags: route
