---
# Create BuildConfigs for an app

- name: Make sure build configs exist
  k8s:
    definition: "{{ lookup('template', item) | from_yaml }}"
    state: present
  with_items: "{{ builds }}"
  when: builds is defined
  tags: build
