---
# Create static routes for services of an app

- name: "Make sure static route exists for the '{{ app.name }}' app with all prefixes"
  include_tasks: tasks/deploy_patch_route.yml
  loop: "{{ blue_green_route_prefixes }}"
  loop_control:
    loop_var: prefix
  when: routes | length > 0 and app.settings.is_blue_green_compatible | default(True)
  tags: route

- name: "Make sure static route exists for the '{{ app.name }}' app"
  include_tasks: tasks/deploy_patch_route.yml
  when: routes | length > 0 and not app.settings.is_blue_green_compatible | default(True)
  tags: route
