---
# Create static routes for services of an app

- name: Make sure static route exists for app[{{ app.name }}]
  openshift_raw:
    force: true
    definition: "{{ lookup('template', 'apps/_common/templates/route/main.yml.j2') | from_yaml }}"
    state: present
  with_nested:
    - "{{ app.services }}"
    - [ 'previous', 'current', 'next' ]
  when: item.0.host is defined
  tags: route
