---
# create the database variable for an app

# Select the environment matching the current env_type: environments | json_query(\"[?name=='\" ~ env_type ~ \"'] | [0]\")
- name: Append database to databases vault
  set_fact:
    databases: "{{ databases | default({}) | merge_with_database(item, app.name, customer, environments | json_query(\"[?name=='\" ~ env_type ~ \"'] | [0]\")) }}"
  loop: "{{ app.settings.databases }}"
  when: app.settings.databases is defined
