---
# Create secrets to login to private docker registries

- name: Retrieve registries vault file
  stat:
    path: "group_vars/customer/{{ customer }}/{{ env_type }}/secrets/registries.vault.yml"
  register: registries_vault

- block:
    - name: Check if registries vault exists
      debug:
        msg: "No registries vault is associated with the project"
    - meta: end_play
  when: not registries_vault.stat.exists

- name: Import registries variable
  include_vars:
    file: "{{ registries_vault.stat.path }}"

- include_tasks: tasks/create_docker_registry_secret.yml
  loop: "{{ registries }}"
  loop_control:
    loop_var: registry
