---
# Create secrets to login to private docker registries

- name: Retrieve registries vault file
  ansible.builtin.stat:
    path: "group_vars/customer/{{ customer }}/{{ env_type }}/secrets/registries.vault.yml"
  register: registries_vault

- name: Check if registries vault exists
  block:
    - name: End play debug error message
      ansible.builtin.debug:
        msg: "No registries vault is associated with the namespace"
    - name: Exit playbook
      ansible.builtin.meta: end_play
  when: not registries_vault.stat.exists

- name: Import registries variable
  ansible.builtin.include_vars:
    file: "{{ registries_vault.stat.path }}"

- name: Create secrets for Docker registries
  ansible.builtin.include_tasks: tasks/create_docker_registry_secret.yml
  loop: "{{ registries }}"
  loop_control:
    loop_var: registry
