---
# Create Docker registry secret
#
# Nota bene: we expect the registry variable to be set

- name: Debug registry
  ansible.builtin.debug:
    var: registry
    verbosity: 2

- name: Set Docker config for registry {{ registry.name }}
  ansible.builtin.set_fact:
    docker_config: "{
      'auths': {
        '{{ registry.server }}': {
          'auth': '{{ (registry.username + ':' + registry.password) | b64encode }}'
        }
      }
    }"

- name: Debug docker_config
  ansible.builtin.debug:
    var: docker_config
    verbosity: 2

- name: Create secret for registry {{ registry.name }}
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ registry.name }}"
        namespace: "{{ namespace_name }}"
      data:
        .dockerconfigjson: "{{ docker_config | to_json | b64encode }}"
      type: kubernetes.io/dockerconfigjson
