---
# Get deployment_stamp from a route

- name: Get deployment_stamp from route[{{ app.name }}-{{ prefix }}]
  openshift_raw:
    definition: "{{ lookup('template', 'templates/openshift/common/utils/get_deployment_stamp_from_route.yml.j2') | from_yaml }}"
  register: app_route

- name: set_fact app_route_deployment_stamp
  set_fact:
    app_route_deployment_stamp: "{{ app_route.result.metadata.labels.deployment_stamp }}"

- name: Print app_route_deployment_stamp
  debug: msg="[{{ app.name }}] route[{{ app.name }}-{{ prefix }}] app_route_deployment_stamp[{{ app_route_deployment_stamp }}]"
