---
# Get deployment_stamp from a route

- name: Get deployment_stamp of route[{{ app.name }}-{{ prefixe }}]
  openshift_raw:
    definition: "{{ lookup('template', 'templates/openshift/common/utils/get_deployment_stamp_form_route.yml.j2') | from_yaml }}"
  register: my_route

- name: set_fact route_deployment_stamp
  set_fact:
    route_deployment_stamp: "{{ my_route.result.metadata.labels.deployment_stamp }}"

- name: Print route_deployment_stamp
  debug: msg="[{{ app.name }}] route[{{ app.name }}-{{ prefixe }}] route_deployment_stamp[{{ route_deployment_stamp }}]"
