---
# Get deployment_stamp from a static service

# An application can define several static services. (e.g. two static services with
# two different routes). Our goal here is to get the deployment_stamp of a
# deployed stack by getting a service object. We retrieve the service and it will
# be labelled with the deploy_stamp we are looking for.
- name: Get static service for application {{ app.name }} with prefix {{ prefix }}
  k8s_info:
    api_version: "v1"
    namespace: "{{ project_name }}"
    kind: "Service"
    label_selectors:
      - type=static-service
      - app={{ app.name }}
      - service_prefix={{ prefix }}
      - "!acme.openshift.io/temporary"
  register: app_service
  when: static_services | length > 0 and app.settings.is_blue_green_compatible | default(True)

# app_deployment_stamp must be defined otherwise all script dependending on this one will fail
- name: Initialize app_deployment_stamp
  set_fact:
    app_deployment_stamp: ""

- name: Set app_deployment_stamp
  set_fact:
    app_deployment_stamp: "{{ (app_service.resources | first ).metadata.labels.deployment_stamp | default(none) }}"
  when: app_service.resources is defined and app_service.resources | length >= 1

- name: "Set {{ prefix }}_app_deployment_stamp"
  set_fact:
    "{{ prefix }}_app_deployment_stamp": "{{ app_deployment_stamp }}"

- name: Print app_deployment_stamp
  debug:
    msg: "[{{ app.name }}] app_deployment_stamp[{{ app_deployment_stamp }}]"
  when: app_deployment_stamp is defined
