---
# Patch routes of all services from a single app to the new deployment_stamp

- name: "Patching routes with prefix {{ prefix }} for the {{ app.name }} application with deployment_stamp {{ deployment_stamp }}"
  openshift_raw:
    force: true
    definition: "{{ lookup('template', route_template) | from_yaml }}"
    state: present
  loop: "{{ routes }}"
  loop_control:
    loop_var: route_template
  when: routes | length > 0
  tags: route
