---
# tasks for managing apps
# Args:
#   deployment_state:
#     - present : default value, all objects are created
#     - 'absent': all objects are deleted
#   deployment_stamp : the stamp of the object we going to creat or delete

- name: "OpenShift objects with deployment_stamp[{{ deployment_stamp }}] must be {{ deployment_state | default('present') }}"
  openshift_raw:
    definition: "{{ lookup('template', 'templates/' + item + '.j2') | from_yaml }}"
    state: "{{ deployment_state | default('present') }}"
  with_items:
    - "{{ openshift_deployments }}"
    - "{{ openshift_services }}"
    - "{{ openshift_jobs }}"
  when: item is not none
