---
# Patch routes of all services from a single app to the new deployment_stamp

- name: "[{{ app.name }}] Patch route[{{ app.name }}-{{ prefix }}] with deployment_stamp[{{ deployment_stamp }}]"
  openshift_raw:
    force: true
    definition: "{{ lookup('template', 'templates/openshift/common/route/main.yml.j2') | from_yaml }}"
    state: present
  with_nested:
    - "{{ app.services }}"
    - "{{ prefix }}"
  when: item.0.host is defined
