---
# Get deployment_stamp from a route

# An application can define several routes (e.g. two services with two
# different routes). Our goal here is to get the deployment_stamp of a
# deployed stack by getting a route object. We first retrieve a route and
# then the service targeted by this route. TThis service will be labelled with the
# deploy_stamp we are looking for.
- name: Get route for application {{ app.name }} with prefix {{ prefix }}
  k8s_info:
    api_version: "v1"
    namespace: "{{ project_name }}"
    kind: "Route"
    label_selectors:
      - app={{ app.name }}
      - route_prefix={{ prefix }}
  register: app_route
  when: routes | length > 0 and app.settings.is_blue_green_compatible | default(True)

- name: Get targeted service
  k8s_info:
    api_version: "v1"
    namespace: "{{ project_name }}"
    kind: "Service"
    name: "{{ ( app_route.resources | first ).spec.to.name }}"
  register: targeted_service
  when: app_route.resources is defined

# app_deployment_stamp must be defined otherwise all script dependending on this one will fail
- name: Initialize app_deployment_stamp
  set_fact:
    app_deployment_stamp: ""

- name: Set app_deployment_stamp
  set_fact:
    app_deployment_stamp: "{{ (targeted_service.resources | first ).metadata.labels.deployment_stamp | default(none) }}"
  when: targeted_service.resources is defined and targeted_service.resources | length == 1

- name: "Set {{ prefix }}_app_deployment_stamp"
  set_fact:
    "{{ prefix }}_app_deployment_stamp": "{{ app_deployment_stamp }}"

- name: Print app_deployment_stamp
  debug:
    msg: "[{{ app.name }}] app_deployment_stamp[{{ app_deployment_stamp }}]"
  when: app_deployment_stamp is defined
