# FIXME: we've defined "prefix" to be able to render all templates, this
# variable should be called url_prefix instead and must default to "next" See:
# https://github.com/openfun/arnold/issues/118
- name: set Prefix
  set_fact:
    prefix: "next"
  when: prefix is not defined

# Remove empty rendered templates (e.g. inactivated for an env_type)
- name: Ignore empty rendered templates
  set_fact:
    path: "{{ item }}"
  register: filtered_templates
  with_items: "{{ raw_templates }}"
  when: lookup('template', item) | length > 1
  tags: deploy

- name: Update templates list for this app
  set_fact:
    templates: "{{ filtered_templates | json_query('results[*].ansible_facts.path') | list }}"
