# Get objects for an application

# Secrets require loading application vaults to be rendered. They are treated
# separately and should not be included here.
- name: Set templates list for this app (except secrets)
  set_fact:
    raw_templates: "{{ \
      app | json_query('services[*].templates[]') | list | \
      map('regex_search', '.*/(?!.*secret).*\\.yml\\.j2$') | select('string') | list \
      }}"
  tags: deploy

- include_tasks: tasks/filter_empty_templates_for_app.yml

- name: Set OpenShift objects to manage
  set_fact:
    builds: "{{ templates | map('regex_search', '.*/bc.*\\.yml\\.j2$') | select('string') | list }}"
    deployments: "{{ templates | map('regex_search', '.*/dc.*\\.yml\\.j2$') | select('string') | list }}"
    endpoints: "{{ templates | map('regex_search', '.*/ep.*\\.yml\\.j2$') | select('string') | list }}"
    services: "{{ templates | map('regex_search', '.*/svc.*\\.yml\\.j2$') | select('string') | list }}"
    streams: "{{ templates | map('regex_search', '.*/is.*\\.yml\\.j2$') | select('string') | list }}"
    jobs: "{{ templates | map('regex_search', '.*/job_.*\\.yml\\.j2$') | select('string') | list }}"
    routes: "{{ templates | map('regex_search', '.*/route.*\\.yml\\.j2$') | select('string') | list }}"
  tags:
    - deploy
    - build
    - deployment
    - endpoint
    - service
    - stream
    - job
    - route

- name: Display OpenShift's builds for this app
  debug:
    var: builds
    verbosity: 2
  when: builds
  tags:
    - deploy
    - build

- name: Display OpenShift's deployments for this app
  debug:
    var: deployments
    verbosity: 2
  when: deployments
  tags:
    - deploy
    - deployment

- name: Display OpenShift's endpoints for this app
  debug:
    var: endpoints
    verbosity: 2
  when: deployments
  tags:
    - deploy
    - endpoint

- name: Display OpenShift's services for this app
  debug:
    var: services
    verbosity: 2
  when: services
  tags:
    - deploy
    - service

- name: Display OpenShift's image streams for this app
  debug:
    var: streams
    verbosity: 2
  when: streams
  tags:
    - deploy
    - stream

- name: Display OpenShift's jobs for this app
  debug:
    var: jobs
    verbosity: 2
  when: jobs
  tags:
    - deploy
    - job

- name: Display OpenShift's routes for this app
  debug:
    var: routes
    verbosity: 2
  when: routes
  tags:
    - deploy
    - route
