# Get objects for an application

- name: Set templates list for this app
  set_fact:
    raw_templates: "{{ app | json_query('services[*].templates[]') | list }}"
  tags: deploy

# Remove empty rendered templates (e.g. inactivated for an env_type)
- name: Ignore empty rendered templates
  set_fact:
    # FIXME: we've defined "prefix" to be able to render all templates, this
    # variable should be called url_prefix instead and must default to "next"
    # See: https://github.com/openfun/arnold/issues/118
    prefix: "next"
    path: "{{ item }}"
  register: filtered_templates
  with_items: "{{ raw_templates }}"
  when: lookup('template', item) | length > 1
  tags: deploy

- name: Update templates list for this app
  set_fact:
    templates: "{{ filtered_templates | json_query('results[*].ansible_facts.path') | list }}"

- name: Set OpenShift objects to manage
  set_fact:
    builds: "{{ templates | map('regex_search', '.*/bc.*\\.yml\\.j2$') | select('string') | list }}"
    deployments: "{{ templates | map('regex_search', '.*/dc.*\\.yml\\.j2$') | select('string') | list }}"
    endpoints: "{{ templates | map('regex_search', '.*/ep.*\\.yml\\.j2$') | select('string') | list }}"
    services: "{{ templates | map('regex_search', '.*/svc\\.yml\\.j2$') | select('string') | list }}"
    streams: "{{ templates | map('regex_search', '.*/is.*\\.yml\\.j2$') | select('string') | list }}"
    jobs: "{{ templates | map('regex_search', '.*/job_.*\\.yml\\.j2$') | select('string') | list }}"
    routes: "{{ templates | map('regex_search', '.*/route.*\\.yml\\.j2$') | select('string') | list }}"
    secrets: "{{ templates | map('regex_search', '.*/secret.*\\.yml\\.j2$') | select('string') | list }}"
  tags:
    - deploy
    - build
    - deployment
    - endpoint
    - service
    - stream
    - job
    - route
    - secret

- name: Display OpenShift's builds for this app
  debug:
    msg: "{{ builds | to_nice_yaml}}"
    verbosity: 2
  when: builds
  tags:
    - deploy
    - build

- name: Display OpenShift's deployments for this app
  debug:
    msg: "{{ deployments | to_nice_yaml }}"
    verbosity: 2
  when: deployments
  tags:
    - deploy
    - deployment

- name: Display OpenShift's endpoints for this app
  debug:
    msg: "{{ endpoints | to_nice_yaml }}"
    verbosity: 2
  when: deployments
  tags:
    - deploy
    - endpoint

- name: Display OpenShift's services for this app
  debug:
    msg: "{{ services | to_nice_yaml }}"
    verbosity: 2
  when: services
  tags:
    - deploy
    - service

- name: Display OpenShift's image streams for this app
  debug:
    msg: "{{ streams | to_nice_yaml }}"
    verbosity: 2
  when: streams
  tags:
    - deploy
    - stream

- name: Display OpenShift's jobs for this app
  debug:
    msg: "{{ jobs | to_nice_yaml }}"
    verbosity: 2
  when: jobs
  tags:
    - deploy
    - job

- name: Display OpenShift's routes for this app
  debug:
    msg: "{{ routes | to_nice_yaml }}"
    verbosity: 2
  when: routes
  tags:
    - deploy
    - route

- name: Display OpenShift's secrets for this app
  debug:
    msg: "{{ secrets | to_nice_yaml }}"
    verbosity: 2
  when: secrets
  tags:
    - deploy
    - secret
