- include_tasks: tasks/set_vault_for_app.yml

# Vault variables are loaded namespaced, i.e. injected in a variable named:
# {{ app.name }}_VAULT, e.g. EDXAPP_VAULT for the edxapp application. To access
# a vault variable, you will need to add its namespace first, e.g.
# EDXAPP_VAULT.MONGODB_NAME
- name: Decrypt vaulted credentials for the given customer and environment
  include_vars:
    file: "{{ app_vault.stat.path }}"
    name: "{{ app.name | upper }}_VAULT"
  when: app_vault.stat is defined and app_vault.stat.exists and app_vault.stat.isreg

- include_tasks: tasks/set_htpasswd_path_for_app.yml

- name: Test htpasswd target file for app
  stat:
    path: "{{ app_htpasswd_file_path }}"
  register: app_htpasswd_file
  tags: htpasswd

- name: Set application htpasswd variable
  set_fact:
    "{{ app.name }}_htpasswd": "{{ app_htpasswd_file.stat.path }}"
  # Only set this variable when the htpasswd file exists and is a regular file
  when: activate_http_basic_auth and app_htpasswd_file.stat.exists and app_htpasswd_file.stat.isreg
  tags: htpasswd
