# Get objects for an application

# Secrets require loading application vaults to be rendered. They are treated
# separately and should not be included here.
- name: Set templates list for this app (except secrets)
  ansible.builtin.set_fact:
    raw_templates: "{{ \
      app | json_query('services[*].templates[]') | list | \
      map('regex_search', '.*/(?!.*secret).*\\.yml\\.j2$') | select('string') | list \
      }}"
  tags: deploy

- name: Filter empty templates for app
  ansible.builtin.include_tasks: tasks/filter_empty_templates_for_app.yml

- name: Set k8s objects to manage
  ansible.builtin.set_fact:
    configmaps: "{{ templates | map('regex_search', '.*/cm.*\\.yml\\.j2$') | select('string') | list }}"
    deployments: "{{ templates | map('regex_search', '.*/deploy.*\\.yml\\.j2$') | select('string') | list }}"
    endpoints: "{{ templates | map('regex_search', '.*/ep.*\\.yml\\.j2$') | select('string') | list }}"
    services: "{{ templates | map('regex_search', '.*/svc.*\\.yml\\.j2$') | select('string') | list }}"
    statefulsets: "{{ templates | map('regex_search', '.*/sts.*\\.yml\\.j2$') | select('string') | list }}"
    static_services: "{{ templates | map('regex_search', '.*/static-svc.*\\.yml\\.j2$') | select('string') | list }}"
    jobs: "{{ templates | map('regex_search', '.*/job_.*\\.yml\\.j2$') | select('string') | list }}"
    cronjobs: "{{ templates | map('regex_search', '.*/cronjob_.*\\.yml\\.j2$') | select('string') | list }}"
    ingresses: "{{ templates | map('regex_search', '.*/ingress.*\\.yml\\.j2$') | select('string') | list }}"
    rbacs: "{{ templates | map('regex_search', '.*/rbac.*\\.yml\\.j2$') | select('string') | list }}"
  tags:
    - configmap
    - deploy
    - deployment
    - endpoint
    - job
    - ingress
    - rbac
    - service
    - statefulset

- name: Display k8s's configmaps for this app
  ansible.builtin.debug:
    var: configmaps
    verbosity: 2
  when: configmaps is defined
  tags:
    - deploy
    - configmap

- name: Display k8s's deployments for this app
  ansible.builtin.debug:
    var: deployments
    verbosity: 2
  when: deployments is defined
  tags:
    - deploy
    - deployment

- name: Display k8s's statefulsets for this app
  ansible.builtin.debug:
    var: statefulsets
    verbosity: 2
  when: deployments is defined
  tags:
    - deploy
    - statefulset

- name: Display k8s's endpoints for this app
  ansible.builtin.debug:
    var: endpoints
    verbosity: 2
  when: deployments is defined
  tags:
    - deploy
    - endpoint

- name: Display k8s's services for this app
  ansible.builtin.debug:
    var: services
    verbosity: 2
  when: services is defined
  tags:
    - deploy
    - service

- name: Display k8s's jobs for this app
  ansible.builtin.debug:
    var: jobs
    verbosity: 2
  when: jobs is defined
  tags:
    - deploy
    - job

- name: Display k8s's cronjobs for this app
  ansible.builtin.debug:
    var: cronjobs
    verbosity: 2
  when: cronjobs is defined
  tags:
    - deploy
    - cronjob

- name: Display K8S ingresses for this app
  ansible.builtin.debug:
    var: ingresses
    verbosity: 2
  when: ingresses is defined
  tags:
    - deploy
    - ingress

- name: Display K8S rbac for this app
  ansible.builtin.debug:
    var: rbacs
    verbosity: 2
  when: rbacs is defined
  tags:
    - deploy
    - rbac
