---
# Patch app dest static service with src stack

- include_tasks: deploy_get_stamp_from_static_service.yml
  vars:
    prefix: next
  tags: switch

- include_tasks: switch_static_service.yml
  vars:
    prefix_service_src:  "{{ prefix_service.src }}"
    prefix_service_dest: "{{ prefix_service.dest }}"
    update_src: "{{ prefix_route.update_src | default(True)}}"
  with_items:
    - src:  current
      dest: next
      update_src: False
    - src:  previous
      dest: current
  loop_control:
    loop_var: prefix_service

- include_tasks: delete_app.yml
  vars:
    app_deployment_stamp: "{{ next_app_deployment_stamp }}"
