---
# Patch app dest routes with src stack

- include_tasks: deploy_get_stamp_from_route.yml
  vars:
    prefix: next
  tags: switch

- name: Save next_app_deployment_stamp
  set_fact:
    next_app_deployment_stamp: "{{ app_deployment_stamp }}"

- include_tasks: switch_route.yml
  vars:
    prefix_route_src:  "{{ prefix_route.src }}"
    prefix_route_dest: "{{ prefix_route.dest }}"
  with_items:
    - src:  current
      dest: next
    - src:  previous
      dest: current
  loop_control:
    loop_var: prefix_route

- include_tasks: delete_app.yml
  vars:
    app_deployment_stamp: "{{ next_app_deployment_stamp }}"
