---
# Patch app dest routes with src stack

- include_tasks: deploy_get_stamp_from_route.yml
  vars:
    prefix: "previous"
  tags: switch

- include_tasks: switch_route.yml
  vars:
    prefix_route_src:  "{{ prefix_route.src }}"
    prefix_route_dest: "{{ prefix_route.dest }}"
    update_src: "{{ prefix_route.update_src | default(True)}}"
  with_items:
    - src:  current
      dest: previous
      update_src: False
    - src:  next
      dest: current
  loop_control:
    loop_var: prefix_route

- include_tasks: delete_app.yml
  vars:
    app_deployment_stamp: "{{ previous_app_deployment_stamp }}"
