---
# Patch app dest routes with src stack

- include_tasks: deploy_get_stamp_from_route.yml
  vars:
    prefix: "previous"
  tags: switch

- name: Save previous_app_deployment_stamp
  set_fact:
    previous_app_deployment_stamp: "{{ app_deployment_stamp }}"

- include_tasks: switch_route.yml
  vars:
    prefix_route_src:  "{{ prefix_route.src }}"
    prefix_route_dest: "{{ prefix_route.dest }}"
    tasks:
      - switch_routes
  with_items:
    - src:  current
      dest: previous
    - src:  next
      dest: current
  loop_control:
    loop_var: prefix_route

- include_tasks: delete_app.yml
  vars:
    app_deployment_stamp: "{{ previous_app_deployment_stamp }}"
