---
# Patch app dest routes with src stack

- include_tasks: deploy_get_stamp_from_route.yml
  vars:
    prefixe: "previous"
  tags: switch

- name: save previous_route_deployment_stamp
  set_fact:
    previous_route_deployment_stamp: "{{ route_deployment_stamp }}"

- include_tasks: switch_route.yml
  vars:
    prefixe_route_src:  "{{ prefixe_route.src }}"
    prefixe_route_dest: "{{ prefixe_route.dest }}"
    tasks:
      - switch_routes
  with_items:
    - src:  current
      dest: previous
    - src:  next
      dest: current
  loop_control:
    loop_var: prefixe_route

- include_tasks: delete_app.yml
  vars:
    route_deployment_stamp: "{{ previous_route_deployment_stamp }}"
