# Variables specific to the eugene customer in development env_type

apps:
  - name: ashley
  - name: mailcatcher
  - name: marsha
  - name: forum
  - name: richie
  - name: learninglocker
  - name: moodlenet
  - name: nextcloud
  - name: etherpad
  - name: edxapp
    services:
      - name: cms
        # We override default ConfigMaps for this customer/env_type
        #
        # Nota bene: file paths are not enforced, but the override mecanism
        # implies that the file names are identical, e.g. docker_run.py.j2
        configs:
          - group_vars/customer/eugene/development/configs/edxapp/cms/docker_run.py.j2
          - group_vars/customer/eugene/development/configs/edxapp/cms/settings.yml.j2
      - name: lms
        configs:
          - group_vars/customer/eugene/development/configs/edxapp/lms/docker_run.py.j2
          - group_vars/customer/eugene/development/configs/edxapp/lms/settings.yml.j2
  - name: redis
  - name: hello
  - name: edxec
  - name: elasticsearch
  - name: kibana

# While deploying edxapp separately from the forum, those vars are required to
# compile custom configMaps
forum_host: "forum.{{ project_name}}.{{ domain_name }}"
forum_port: 9292

# increase edxapp data volume size
edxapp_data_volume_size: 4Gi
