# URL
domain_name: oc.openfun.fr

# OpenShift routes_aliases example
#
# openshift_routes_aliases:
#   # main domain to redirect to (this route must exist)
#   - route: www.maindomain.tld
#     # aliases that will redirect to the previous 'route' definition
#     aliases:
#       - maindomain.tld
#       - main-domain.tld
#
#   - route: main_route
#     aliases:
#       - alias_1
#       - alias_2
openshift_routes_aliases:
  # No route aliases
