# FIXME: we have deactivated plugins test coverage as the container user is
# not allowed to write to /app/.coverage and CircleCI does not allow to mount
# volumes with "docker run" commands.
test-plugins:
  <<: *defaults

  steps:
    - checkout
    - *dind
    - *attach_workspace
    - *docker_load
    - *ci_env
    - run:
        name: Run unit tests for local plugins
        command: |
          docker run --rm \
            --tmpfs /app/.pytest_cache \
            "${ARNOLD_IMAGE}" \
            python -m pytest --no-cov
