# Variables specific to the eugene customer
# Eugene is a demo site with default configuration
project_display_name: "Eugene ({{ env_type }})"
project_description: "A demo project with a typical installation ({{ env_type }})"

apps:
  - name: richie
