# Variables specific to the eugene customer
# Eugene is a demo site with default configuration

# Marsha
# We don't want to require an AWS SSH key for testing
marsha_should_sign_requests: false

# Nextcloud
nextcloud_database_name: nextcloud

# Elasticsearch
# Limit memory usage
elasticsearch_java_opts:
  - "-Xms64m"
  - "-Xmx64m"
elasticsearch_image_name: "elasticsearch"
elasticsearch_image_tag: "7.7.0"


# Network policy
network_policy_per_namespace_enabled: true

# UID to use for running containers on k8s.
container_uid: 10100
