# CI environment variables
domain_name: "{{ lookup('env', 'K8S_DOMAIN') }}.nip.io"

# The CI environment is not supposed to be interactive
skip_verification: True

# OpenShift's internal docker registry server
#
# FIXME: use docker registry server IP address instead of the service name (i.e.
# docker-registry.default.svc) to prevent oc cluster DNS issues
internal_docker_registry: "172.30.1.1:5000"
