# CI environment variables
project_description: "A minimal project to test apps bootstrapping ({{ env_type }})"
domain_name: "{{ lookup('env', 'OPENSHIFT_DOMAIN') }}.nip.io"

apps:
  - name: hello
  - name: richie
  - name: edxapp
  - name: redis
