# Variables specific to feature environments

# Only in feature environment do we add the feature title to the hosts
lms_host: "{{ project_name }}-lms--{{ feature_title }}.{{ domain_name }}"
cms_host: "{{ project_name }}-cms--{{ feature_title }}.{{ domain_name }}"
