# Variables specific to the hello customer
# Hello is a demo site with default configuration
# for a minimal dev app
project_display_name: "Hello ({{ env_type }})"
project_description: "A minimal project with a hello-world app ({{ env_type }})"

apps:
  - name: hello
    services:
      - name:       hello
        host:       "hello.{{ project_name }}.{{ domain_name }}"

## _____ soon deprecated below _________________________________________________
hello_host: "{{ project_name }}.{{ domain_name }}"
hello_port: "8080"
hello_msg:  "Hello OpenShift! by Arnold"

nginx_ports:
  - "{{ aliases_port }}"

# Openshift template files
openshift_deployments:
  - openshift/hello/dc/hello.yml
  - openshift/richie/dc/elasticsearch.yml
  - openshift/richie/dc/nginx.yml
  - openshift/richie/dc/richie.yml
openshift_endpoints:
openshift_jobs:
openshift_routes:
  - openshift/hello/route/hello.yml
  - openshift/richie/route/richie.yml
openshift_services:
  - openshift/hello/svc/hello.yml
  - openshift/richie/svc/elasticsearch.yml
  - openshift/richie/svc/nginx.yml
  - openshift/richie/svc/richie.yml
openshift_volumes:
  - openshift/richie/pvc/media.yml
  - openshift/richie/pvc/static.yml
